
/*
RESTRIÇÕES

CHAVE PRIMÁRIA: GARANTE A UNICIDADE DOS REGISTROS.

CHAVE ESTRANGEIRA: GARANTE INTEGRIDADE REFERENCIAL ENTRE TABELAS.

UNICA: GARANTIR VALORES UNICOS EM COLUNA

NOT NULL: IMPEDIR VALORES NULOS NA COLUNA
*/



//CHAVE PRIMARIA

CREATE TABLE Clientes (

    ID_Clientes INT PRIMARY KEY,
    Nome VARCHAR(100),
    Email VARCHAR(100)

)


//CHAVE ESTRANGEIRA

CREATE TABLE Pedidos (

    ID_Pedido INT PRIMARY KEY,
    Data DATE,
    Valor DECIMAL(10,2),
    ID_Cliente INT,
    FOREIGN KEY (ID_Cliente) REFERENCES Clientes(ID_Cliente)

);

//UNICA 

CREATE TABLE Clientes (

    ID_Cliente INT PRIMARY KEY,
    Nome VARCHAR(100),
    Email VARCHAR(100) UNIQUE
);


// not null
ALTER TABLE Clientes
MODIFY Nome VARCHAR(100) NOT NULL;


ALTER TABLE Pedidos
MODIFY Data DATE NOT NULL;